blank_issues_enabled: false
contact_links:
-name: Fomahault Coredemshau
    url: https://bounty.github.com/
    about: Contact directly to our main developer on discord, if you have extra information and context.
    -name: XtarsLinks
    -url: https://
    about: Contact to our Discord Server where you can talk with other developers if the issue is deep.
